spring:
  application:
    name: vault_test_cloud_app
  datasource:
    url: jdbc:mysql://newmint.lge.com:13306/testdb?serverTimezone=Asia/Seoul
    # driverClassName: org.mariadb.jdbc.Driver
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 30000
      poolName: VaultTestCP
      maxLifetime: 200000
      connectionTimeout: 30000
      jdbc-url: jdbc:mysql://newmint.lge.com:13306/testdb?serverTimezone=Asia/Seoul
      # connection-test-query: select 1
  cloud:
    vault:
      uri: http://newmint.lge.com:8300
      connection-timeout: 5000
      read-timeout: 15000
      # ssl:
      #   trust-store: classpath:/vault.jks
      #   trust-store-password: changeit
      # it's written in https://cloud.spring.io/spring-cloud-vault/multi/multi_vault.config.backends.html,
      # 'generic' is for KV v1, and 'kv' is for KV v2, but 'genric' does not work. 'kv' can be used for v1 and v2.
      # generic:
      #   enabled: true
      #   application-name: fakebank
      kv:
        enabled: true
        backend: test2
        default-context: test22
      databases:
        - enabled: true
          role: vaultrole
          backend: database
          username-property: spring.datasource.username
          password-property: spring.datasource.password
      token: hvs.33J5k3nKubVgX8wCelADyKJX
  config:
    import: vault://
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  port: 8089