spring:
  application:
    name: vault_test_cloud_app
  datasource:
    url: jdbc:mysql://192.168.0.115:13306/testdb?serverTimezone=Asia/Seoul
    hikari:
      connection-test-query: select 1
      idle-timeout: 5000
      max-lifetime: 120000
      maximum-pool-size: 5
      minimum-idle: 5
  cloud:
    vault:
      uri: http://192.168.0.115:8200
      connection-timeout: 5000
      read-timeout: 15000
      # ssl:
      #   trust-store: classpath:/vault.jks
      #   trust-store-password: changeit
      # it's written in https://cloud.spring.io/spring-cloud-vault/multi/multi_vault.config.backends.html,
      # 'generic' is KV v1, and 'kv' is KV v2, but genric does work. 'kv' can be used for v1 and v2.
      # generic:
      #   enabled: true
      #   application-name: fakebank
      kv:
        enabled: true
        backend: test2
        default-context: test22
      database:
        enabled: true
        role: vaultrole
        backend: database
        username-property: spring.datasource.username
        password-property: spring.datasource.password
      token: s.5yWHkcZ1LOAAGQQkYuC3LmQR
  config:
    import: vault://
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  port: 8089